---
- name: "Create {{ profile_svdir }}"
  file:
    path: "{{ profile_svdir }}"
    state: directory

- name: "Register list of cloned services"
  find:
    paths: "{{ profile_svsrc }}"
    depth: 1
    file_type: "directory"
    recurse: true
  register: services_dirs

- name: "Enable services"
  file:
    src: "{{ item['path'] }}"
    dest: "{{ profile_svdir }}/{{ item['path'] | basename }}"
    state: link
  loop: "{{ services_dirs }}"
  notify: Restart runsvdir process
