#!/usr/bin/env bash

eval "$(starship init bash)" # Enable starship

complete -c doas # Doas completion commands

load() {
	[ -f "$1" ] && source "$1"
	[ -d "$1" ] &&
		while read -r i; do
			source "$i"
		done < <(find "$1" -type f)

}
load "${XDG_CONFIG_HOME:-~/.config}/shell/load/"  # Load functions

unset -f load # Delete load()

# Fix ls colors
eval "$(dircolors)"
