#!/usr/bin/env sh

CONFIG_HOME="${XDG_CONFIG_HOME:-~/.config}/x11"

resources="$CONFIG_HOME/xresources"

. "$CONFIG_HOME/autostart"

[ -f "$resources" ] && xrdb -merge "$resources"

if [ "$(command -v dwm)" ]; then
	dwmblocks &
	exec dwm
else
	echo "Install a DE/WM"
fi
