---
# tasks file for git_server

- name: "Create a git user"
  become: true
  user:
    name: git

- name: "Install acl package"
  become: true
  community.general.xbps:
    name: acl
    update_cache: true

- block:
    - name: "Create ~/.ssh dir for git user"
      file:
        path: "~/.ssh"
        state: directory
        mode: "0700"
    - name: "Create ~/.ssh/authorized_keys file for git user"
      file:
        path: "~/.ssh/authorized_keys"
        state: touch
        mode: "0600"

    - name: "Add git users' public keys to the ~/.ssh/authorized_keys file"
      ansible.posix.authorized_key:
        user: git
        key: "{{ lookup('file', item['src']) }}"
      when: item['state'] == 'file'
      loop: "{{ lookup('community.general.filetree',
        hostvars['localhost']['git_users_keys_tmpdir'].path) }}"

  become: true
  become_user: git
