#!/usr/bin/env sh

man() {
	LESS_TERMCAP_md="$(
		tput bold
		tput setaf 4
	)" \
	LESS_TERMCAP_me="$(tput sgr0)" \
	LESS_TERMCAP_se="$(
		tput rmso
		tput sgr0
	)" \
	LESS_TERMCAP_us="$(
		tput smul
		tput setaf 6
	)" \
	LESS_TERMCAP_ue="$(
		tput rmul
		tput sgr0
	)" \
		command man "$@"
}
